-- ShalaConnect Database Setup (PostgreSQL)
-- This runs automatically when the postgres container starts for the first time.
-- Tables are auto-created by Hibernate (ddl-auto=update) on first run.
-- Default admin account is seeded automatically by DataSeeder.java:
--   Email:    admin@shalaconnect.in
--   Password: Admin@123
--
-- Change the admin password immediately after first login!
